version: '2'
services:
    web:
        build: .
        ports:
            - "9595:5000"
        volumes:
            - ./www:/code
        depends_on:
            - redis
        restart: always
    redis:
        image: redis
